version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
        - echo Instalando dependencias...
        - npm install
        - npm install -g @angular/cli@15.2.8
  build:
    commands:
        - echo Build started 
        - ng build
        - ls
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes